package com.ef;
// Generated Dec 4, 2017 3:50:18 AM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParserRunId generated by hbm2java
 */
@Embeddable
public class ParserRunId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int runId;
	private String clientIp;

	public ParserRunId() {
	}

	public ParserRunId(int runId, String clientIp) {
		this.runId = runId;
		this.clientIp = clientIp;
	}

	@Column(name = "Run_ID", nullable = false)
	public int getRunId() {
		return this.runId;
	}

	public void setRunId(int runId) {
		this.runId = runId;
	}

	@Column(name = "Client_IP", nullable = false, length = 16)
	public String getClientIp() {
		return this.clientIp;
	}

	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParserRunId))
			return false;
		ParserRunId castOther = (ParserRunId) other;

		return (this.getRunId() == castOther.getRunId())
				&& ((this.getClientIp() == castOther.getClientIp()) || (this.getClientIp() != null
						&& castOther.getClientIp() != null && this.getClientIp().equals(castOther.getClientIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRunId();
		result = 37 * result + (getClientIp() == null ? 0 : this.getClientIp().hashCode());
		return result;
	}

}
