package com.ef;
// Generated Dec 4, 2017 3:50:18 AM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ServerLog generated by hbm2java
 */
@Entity
@Table(name = "server_log", catalog = "wallethub")
public class ServerLog implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date logDateTime;
	private String clientIp;
	private String requestType;
	private Short requestStatus;
	private String userAgent;

	public ServerLog() {
	}

	public ServerLog(Date logDateTime, String clientIp) {
		this.logDateTime = logDateTime;
		this.clientIp = clientIp;
	}

	public ServerLog(Date logDateTime, String clientIp, String requestType, Short requestStatus, String userAgent) {
		this.logDateTime = logDateTime;
		this.clientIp = clientIp;
		this.requestType = requestType;
		this.requestStatus = requestStatus;
		this.userAgent = userAgent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Log_DateTime", nullable = false, length = 19)
	public Date getLogDateTime() {
		return this.logDateTime;
	}

	public void setLogDateTime(Date logDateTime) {
		this.logDateTime = logDateTime;
	}

	@Column(name = "Client_IP", nullable = false, length = 16)
	public String getClientIp() {
		return this.clientIp;
	}

	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	@Column(name = "Request_Type", length = 32)
	public String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	@Column(name = "Request_Status")
	public Short getRequestStatus() {
		return this.requestStatus;
	}

	public void setRequestStatus(Short requestStatus) {
		this.requestStatus = requestStatus;
	}

	@Column(name = "User_Agent", length = 512)
	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ServerLog [id=").append(id).append(", logDateTime=").append(logDateTime).append(", clientIp=")
				.append(clientIp).append(", requestType=").append(requestType).append(", requestStatus=")
				.append(requestStatus).append(", userAgent=").append(userAgent).append("]");
		return builder.toString();
	}

}
